pipeline {
    agent any

    tools {
        maven 'Maven_3.9.6'
        jdk 'JDK_21'
    }

    stages {
        stage('SampleBuildJobs') {
            steps {
                echo 'Building the project...'
            }
        }

        stage('SampleTestJobs') {
            steps {
                git url: 'https://github.com/rajeshbandaru34/CICD.git', branch: 'main'
                dir('CICD') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('SampleDeployJobs') {
            steps {
                echo 'Deploying the project...'
            }
        }

        stage('SampleDeliveryJobs') {
            steps {
                echo 'Delivering the project...'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
            dir('CICD/test-output') {
                publishHTML(target: [
                    reportDir: '.',                  // Current dir is test-output
                    reportFiles: 'index.html',
                    reportName: 'TestNG HTML Report',
                    keepAll: true,
                    alwaysLinkToLastBuild: true,
                    allowMissing: false
                ])
            }
        }

        success {
            echo 'Build was successful!'
        }

        failure {
            echo 'Build failed.'
        }
    }
}