pipeline {
    agent any

    tools {
        maven 'Maven_3.9.6'
        jdk 'JDK_21'
    }

    stages {
        stage('Build & Test') {
            steps {
                git url: 'https://github.com/rajeshbandaru34/CICD.git', branch: 'main'
                bat 'mvn clean test'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
            publishHTML([
                reportDir: 'test-output',
                reportFiles: 'index.html',
                reportName: 'TestNG HTML Report',
                keepAll: true
            ])
        }
        success {
            echo 'Build was successful!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
